### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by kschagen** [rajiv/akamai-cli-certs#3]
When I used "akamai install https://github.com/rajiv/akamai-cli-certs" (OS is OSX) I didn't get any  errors. But when using the command "akamai certs help" i got the following error:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- akamai/api/cps (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
	from /Users/kschagen/.akamai-cli/src/akamai-cli-certs/bin/akamai-certs:2:in `\<main\>'

Would love to test your Akamai cli extension.

**Comment by rajiv** [comment]
which macos version are you running?

**Comment by kschagen** [comment]
$sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1114

**Comment by rajiv** [comment]
i have been unable to replicate this locally. from the error, it seems that either the `akamai-api-cps` gem is not getting installed, or being installed someplace outside the load path.

could you provide some more details with the output of these commands:
`which ruby`
`which gem`
`gem list`
`gem environment`

thanks

**Comment by rajiv** [comment]
you can likely work around the gem install issue by manually running `gem install akamai-api-cps`

**Comment by rajiv** [comment]
this is due to a bug in the install code in the cli. the install command should fail if it cannot find the `bundle` command, but continues without error. see akamai/cli/issues/40.

the correct workaround is to run `gem install bundler` before running `akamai install rajiv/akamai-cli-certs`.

i will update the README to detail this step.
